### ISSUE TITLE
Is this fork being maintained?

### ISSUE THREAD

**Issue by AKST** [tmhedberg/hsenv#51]
Hi, just wondering if this fork is being maintained? there doesn't seem to be much activity on the issue tracker and last commit was a year ago

**Comment by tmhedberg** [comment]
I'm still here, but I'd say the project is basically obsolete. The new breed of Haskell development tools like Cabal sandboxes and Stack have solved the problems hsenv addressed, generally in better ways and with a lot more community momentum. I wouldn't really recommend using this fork anymore, or any other versions of hsenv for that matter. Do you have a particular reason to keep using it?

**Comment by AKST** [comment]
I actually haven't started using it, but was considering. Just looking for something to automate the installation and switching of GHC versions, for the purpose of benchmarking the compilation of different GHC versions. I believe stack doesn't support ghc versions prior to ghc-7.8, but i was unaware of ~~GHC's~~ cabal's ability to do anything like this

**Comment by AKST** [comment]
I'll close the issue since that kind of answers the question, but could you point me in the direction of documentation on this feature? I haven't found anything like it from my searches

**Comment by tmhedberg** [comment]
I don't know how well cabal supports multiple GHC versions; I was thinking of Stack for that. That being said, you can specify the `--with-compiler=<path>` flag to the `cabal configure` and `cabal install` commands to tell it to use a particular version of a compiler that you have installed. I haven't used this feature myself, so maybe there are drawbacks that I'm unaware of. `cabal sandbox` and its subcommands allow you to isolate package installations so that you can have multiple versions of a given package installed for different projects on the system.

**Comment by AKST** [comment]
Yeah I've seen that feature before, but as fair as I'm aware cabal won't download the specific version for you, which is going to be a pain when I set this up in a remote machine and I have to adjust my setup to the different machine as well as install the different binary versions. Nothing impossible just annoying stuff I'd prefer to automate, thanks either way.
